services:
  monitoring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitoring-app
    restart: always
    ports:
      - "8091:8090"
    volumes:
      - ./pb_data:/app/pb_data
    environment:
      - TZ=UTC

networks:
  default:
    name: nginx-proxy-manager_default
    external: true
